import type { ILoggerComponent } from '@well-known-components/interfaces'
import { generateRoot } from '@dcl/content-hash-tree'
import { keccak256Hash } from '@dcl/hashing'
import type { ThirdPartyProps } from '@dcl/schemas'
import { MerkleProof, isThirdParty } from '@dcl/schemas'
import type { BlockchainCollectionThirdParty } from '@dcl/urn-resolver'
import { OK, validationFailed } from '../../../types'
import { getThirdPartyId, toHexBuffer } from '../../../utils'
import type { DeploymentToValidate, OnChainAccessCheckerComponents, ThirdPartyAssetValidateFn } from '../../../types'

async function verifyMerkleProofedEntity(
  components: Pick<OnChainAccessCheckerComponents, 'externalCalls' | 'logs' | 'client' | 'L2'>,
  asset: BlockchainCollectionThirdParty,
  deployment: DeploymentToValidate,
  logger: ILoggerComponent.ILogger
): Promise<boolean> {
  const { timestamp } = deployment.entity
  let verified = false

  if (isThirdParty(deployment.entity.metadata)) {
    const metadata = deployment.entity.metadata as ThirdPartyProps
    const merkleProof = metadata.merkleProof

    if (!MerkleProof.validate(merkleProof)) {
      logger.debug('Merkle proof is not valid', {
        merkleProof: merkleProof
      })
      return false
    }
    const generatedHash = keccak256Hash(metadata, merkleProof.hashingKeys)
    if (merkleProof.entityHash !== generatedHash) {
      logger.debug(`The hash provided in the merkleProof doesn't match the one generated by the validator`, {
        generatedHash,
        entityHash: merkleProof.entityHash
      })
      return false
    }

    const thirdPartyId = getThirdPartyId(asset)

    const bufferedProofs = merkleProof.proof.map((value) => toHexBuffer(value))
    const root = generateRoot(merkleProof.index, merkleProof.entityHash, bufferedProofs)

    const { blockNumberAtDeployment, blockNumberFiveMinBeforeDeployment } =
      await components.client.findBlocksForTimestamp(timestamp, components.L2.blockSearch)

    const validateThirdParty = async (block: number) => {
      try {
        return await components.L2.checker.validateThirdParty(thirdPartyId, root, block)
      } catch (err) {
        logger.warn(err instanceof Error ? err.message : String(err))
        return false
      }
    }

    if (blockNumberAtDeployment) {
      verified = await validateThirdParty(blockNumberAtDeployment)
    }

    if (!verified && blockNumberFiveMinBeforeDeployment) {
      verified = await validateThirdParty(blockNumberFiveMinBeforeDeployment)
    }
  }

  return verified
}

// Verifies merkle-root membership only. The id/content/required-key binding is enforced separately by
// item validation (thirdParty*MerkleProofContentValidateFn); both run in the full validator, so this is
// not a complete security check on its own.
export function createThirdPartyAssetValidateFn(
  components: Pick<OnChainAccessCheckerComponents, 'externalCalls' | 'logs' | 'client' | 'L2'>
): ThirdPartyAssetValidateFn {
  return async function validateFn(asset: BlockchainCollectionThirdParty, deployment: DeploymentToValidate) {
    const logger = components.logs.getLogger('(on-chain) third-party-asset-validation')

    const verified = await verifyMerkleProofedEntity(components, asset, deployment, logger)
    if (!verified) {
      return validationFailed(`Couldn't verify merkle proofed entity for third-party wearable`)
    }
    return OK
  }
}
